[package]
name = "near-runtime-configs"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }

near-primitives = { path = "../primitives" }
near-runtime-fees = { path = "../../runtime/near-runtime-fees" }
near-vm-logic = { path = "../../runtime/near-vm-logic" }

[features]
protocol_feature_alt_bn128 = []
nightly_protocol = []
nightly_protocol_features = ["nightly_protocol", "near-vm-logic/nightly_protocol_features"]